name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    # FIXME: inherit when GitHub Enterprise ships
    secrets: inherit
    with:
      balena_slugs: balenablocks/cert-manager-amd64
      # FIXME: remove when Kubernetes clusters are configured to pull from bh.cr
      docker_images: balena/cert-manager
